yahoojapan/fullock

.gitignore
ChangeLog
lib/flckbaselist.tcc
lib/flckshm.cc
lib/flckshm.h
lib/flckshminit.cc
lib/flckthread.cc
lib/flckthread.h
tests/Makefile.am
tests/forktest.cc
tests/test.sh

n/a
1. Exclusive control in the processing of fl_unlock_rwlock () and fl_list_base () was more strict.(1.0.22)
2. fullock creates one thread for itself at loaded it(dlopen).  
This caused the program to deadlock if the program loaded with fullock forked.  
This bug was fixed by the following method.
- When fullock is unloaded(including at the end of the program), use pthread_cancel() to terminate the thread.
- Use a cleanup handler at exiting thread(use pthread_cleanup_push/pop)
- Use non portable pthread_tryjoin_np function instead of pthread_join
- Use a handler at forking(use pthread_atfork)
- Add a program for test of forking
3. increment version number

Fixed a bug about deadlock at forking

---

lib/flckdbg.cc
lib/flckshm.cc
lib/flckshm.h
lib/flckshminit.cc
lib/flckutil.cc
lib/rwlockrcsv.cc
lib/rwlockrcsv.h

n/a
Fixed a bug in static object initialization order problem (SIOF).
Although it has not happened so far, there was a possibility that SIOF occurred in this library using singleton.
The probability of occurrence in std :: string initialization is high. All logic corresponding to this bug has been fixed. For details of this problem, please refer to [here](https://www.google.com/search?q=static%20initialization%20order%20fiasco).

avoid static object initialization order problem(SIOF)

---

ChangeLog
docs/fullock.3

n/a
- Fixed lintian error in man page about wrong word  
Fixed issue that there was an invalid character in the man page and an error occurred in Lintian.
- Fixed lintian error in man page about wrong word(2)
Refixed issue that there was an invalid character in the man page and an error occurred in Lintian.

Updated files for release 1.0.30

---

lib/flckthread.cc
lib/flckutil.cc

Typos reported by debian lintian. The severity is "wishlist".
Here is an output that I tried debianizd fullock.
```
$ debuild
...
I: libfullock1: spelling-error-in-binary usr/lib/x86_64-linux-gnu/libfullock.so.1.0.36 occured occurred
N: 
N:    Lintian found a spelling error in the given binary. Lintian has a list
N:    of common misspellings that it looks for. It does not have a dictionary
N:    like a spelling checker does.
N:    
N:    If the string containing the spelling error is translated with the help
N:    of gettext or a similar tool, please fix the error in the translations
N:    as well as the English text to avoid making the translations fuzzy. With
N:    gettext, for example, this means you should also fix the spelling
N:    mistake in the corresponding msgids in the *.po …
```

Fixes typos.

---

.github/workflows/build_helper.sh

n/a
There was a bug (variable name error) in the build_helper.sh file, which was fixed.
(As for fullock, it is not affected by this bug.)

Fixed a bug in build_helper.sh

---

.github/workflows/build_helper.sh
lib/flckcommon.h
lib/flckshm.cc

n / a
Functional improvements and bug fixes.
- Changed the default directory of SHM files to `/var/lib/antpickax` (if it doesn't exist, use `/tmp` as before)
- Supports builds on ALPINE images
- Fixed a bug in `build_helper.sh` on Github Actions

Functional improvements and bug fixes

---

.github/workflows/ci.yml

#43 
Changed to not login to DockerHub only for pull requests when building and pushing Docker images on Github Actions.
For PullRequest, this is because you can't read the Github secret.
We also confirmed that there are no IP address rate limit on access to DockerHub from the official Github Actions Runner.
Currently, the login process is not limited to pull requests, although it may change in the future.

Fixed ci.yml for Docker image build/push

---

buildutils/libfullock.postinst
buildutils/libfullock.spec.in
lib/flckshm.cc

n/a
Changed the judgment process of the default SHM directory.
Changed to use `/tmp` instead of creating the `/var/lib/antpickax` directory if it doesn't exist.
And also added the `/var/lib/antpickax` directory to the package.

Fixed to create /var/lib/antpickax at installation

---

ChangeLog

n/a
- Fixed to create /var/lib/antpickax at installation - #48

Updated changelog for v1.0.42

---

configure.ac

n/a
Enabled to customize variables in `configure.ac`.
If the `configure.custom` file exists, it will be loaded.
(currently unused but added to increase availability)

Enabled external customization of variables in configure.ac

---

.github/workflows/ostypevars.sh

n/a
Fixed CentOS 8 build failing.
It was caused by changing the mirror, so I fixed it.

Fixed build error on CentOS8

---

Makefile.am

#72 #73
Revised the definition of `cppcheck` in `Makefile.am`.

Updated Makefile.am about cppcheck

---

configure.ac

n/a
In combination with some OS and runtime, a segmentation fault sometimes occurred when unloading this library.
This depends on the LTO optimization, so I added the `-fno-lto` option.

Added gcc -fno-lto option

---

ChangeLog

n/a
- Supported fedora 37 and dropped support for fedora 35dropped - #81
- Changed CI process flow/OSs and added Alpine OS - #80
- Fixed a bug in rule.in file for debian packaging - #79
- Added gcc -fno-lto option - #78
- [gh-pages] Updated header and footer in comment lines - #77
- Updated header and footer in comment lines - #76
- Updated issue/pullrequest templates - #75
- Updated Makefile.am about cppcheck - #74
- Updated Makefile.am about cppcheck - #73
- Added ShellCheck processing and reviewed cppcheck - #72
- Fixed a bug in build_helper.sh - #71
- Eliminated unnecessary copies in build_helper.sh - #70
- Updated docker/login-action from v1 to v2 - #69
- Fixed a bug in docker_helper.sh and ci.yml - #68
- Shared Docker image build logic with other products - #67
- Re-updated github …

Updated changelog for v1.0.45

---

ChangeLog

#82
- Fixed a bug about publishing in build_helper.sh - #83
- Supported fedora 37 and dropped support for fedora 35dropped - #81
- Changed CI process flow/OSs and added Alpine OS - #80
- Fixed a bug in rule.in file for debian packaging - #79
- Added gcc -fno-lto option - #78
- [gh-pages] Updated header and footer in comment lines - #77
- Updated header and footer in comment lines - #76
- Updated issue/pullrequest templates - #75
- Updated Makefile.am about cppcheck - #74
- Updated Makefile.am about cppcheck - #73
- Added ShellCheck processing and reviewed cppcheck - #72
- Fixed a bug in build_helper.sh - #71
- Eliminated unnecessary copies in build_helper.sh - #70
- Updated docker/login-action from v1 to v2 - #69
- Fixed a bug in docker_helper.sh and ci.yml - #68
- Shared Docker image …

Re-updated changelog for v1.0.45

---

ChangeLog

n/a
- Fixed build_helper.sh for upgrading ruby required package_cloud - #103

Updated changelog for v1.0.55

---

.github/workflows/build_helper.sh

n/a
- Fixed `build_helper.sh`
The minimum Ruby version required for the `package_cloud` command has been changed to 2.7, and `build_helper.sh` has been modified accordingly.

Fixed build_helper.sh for ruby 2.7 required package_cloud

---

ChangeLog

n/a
- Fixed build_helper.sh for ruby 2.7 required package_cloud - #108

Updated changelog for v1.0.57

---

Makefile.am

#111
There was an error in the version determination part of `cppcheck` in `Makefile.am`, which has been corrected.

Fixed Makefile.am about cppcheck version

---

buildutils/APKBUILD.templ.in
buildutils/Dockerfile.templ.in
buildutils/libfullock.postinst
buildutils/libfullock.spec.in

n/a
`/var/run/antpickax` and `/etc/antpickax` have been added to the directories created by the package.

Added a directory to be created by the package

---

lib/flcklistfilelock.h
lib/flcklistlocker.h
lib/flcklistncond.h
lib/flcklistnmtx.h
lib/flcklistofflock.h
lib/flcklistwaiter.h
tests/fcntl_mptest.cc

n/a
The latest cppcheck(v2.11 or 2.14 or later) is falsely detecting a `constParameterPointer` error when specifying `const` using the typedef name of a structure pointer.
Therefore, avoided this by adding an inline suppress.

Avoided latest cppcheck error which maybe a false positive
