- ChangeLog
- lib/flckshm.cc
- make_valiables.sh
#1
- Refixed a bug about deadlock at forking - #1
- Added lib_version_for_link option to make_valiables.sh
- Updated changelog for v1.0.24
> Fixed a bug and Updated changelog for v1.0.24

- ChangeLog
n/a
- Updated ChangeLog for v1.0.28
> Updated files for release 1.0.28

- index.md
- indexja.md
n/a
Fixed some wrong(bad) links(url).
> Fixed bad url links

- .travis.yml
- ChangeLog
- README
- README.md
- buildutils/control.in
- buildutils/debian_build.sh
- buildutils/libfullock.spec.in
- buildutils/make_rpm_changelog.sh
- buildutils/make_variables.sh
- buildutils/rpm_build.sh
- buildutils/travis_builder.sh
- configure.ac
- docs/fullock.3
n/a
- Support packagecloud.io as AntPickax package repository
- Move *.so symbolic link to devel package
- Strictification of spec files
- Stricter debian packages
- Covers the OS and each part dependent on its version in each packaging
- Add rpm dedicated packaging script(local packaging available)
- Changed README
- Changed README.md and added some badge
> Updated files for release 1.0.31

- .travis.yml
- buildutils/travis_builder.sh
#9 
- Changed to execute debian package build only when Release Tag is set.
> Updated files for release 1.0.31(Additional modification)

- .travis.yml
- ChangeLog
- buildutils/debian_build.sh
- buildutils/libfullock.spec.in
- buildutils/make_variables.sh
- buildutils/travis_builder.sh
- configure.ac
n/a
- Deleted lines in spec file which are BuildRoot and Prefix.
- Deleted AC_PROG_LIBTOOL macro from configure.ac
- Updated debian_build.sh, make_variables.sh and travis_builder.sh
- Updated .travis.yml
> Updated files for release 1.0.32

- lib/flckshminit.cc
- lib/flckutil.cc
- lib/flckutil.h
- tests/fullocktest.cc
n/a
- fix typo, warning.
- optimize code ( e.g. doing with "for loop" )
This pull request is a retry of [#14](https://github.com/yahoojapan/fullock/pull/14).
> some small fix(typo and optimize code)

- usage.md
- usageja.md
Fixed wrong command(apt-get) in usage page
> Fixed wrong command in usage page

- ChangeLog
#15 
- some small fix(typo and optimize code) - #15
> Updated files for release 1.0.34

- lib/flckshm.cc
- lib/flckshm.h
- lib/flckutil.cc
- lib/flckutil.h
- lib/fullock.cc
- lib/rwlockrcsv.cc
> Fixed Typo and Comment.

- lib/flckshm.h
- lib/flckshminit.cc
- tests/fullocktest.cc
n/a
The IsLowRobust method returns whether it is Robust mode or not.  
However, this name is misunderstood to be a low level Robust mode check.  
For that reason, we changed IsRobust and the method name clearly.
> Changed method name from IsLowRobust to IsRobust

- README.md
- buildutils/travis_builder.sh
- tests/fullocktest.cc
- tests/test.sh
#23 
Correspondence omission of #23 was addressed.
There was an unnecessary code, so deleted it.
> Fixed misspelling, and etc

- README.md
- lib/flckbaselist.tcc
- lib/flcklistofflock.cc
- lib/flckthread.cc
- lib/flckutil.cc
- tests/cond_mptest.cc
- tests/cond_mttest.cc
- tests/fcntl_mptest.cc
- tests/fcntl_mttest.cc
- tests/fullocktest.cc
- tests/mptest.cc
- tests/mttest.cc
- tests/singletest.cc
n/a
- Fixed cppcheck(1.87) error
- Added fullock overview image in README.md
> Fixed codes for cppcheck 1.87

- lib/flckbaselist.tcc
- lib/flckthread.cc
- lib/flckutil.cc
- lib/rwlockrcsv.cc
- lib/rwlockrcsv.h
- tests/cond_mptest.cc
- tests/cond_mttest.cc
- tests/fullocktest.cc
n/a
Fixed a description error newly detected by cppcheck.
> Fixed bugs detected by cppcheck

- ChangeLog
- README.md
n/a
- Switched Travis CI to Github actions and extended supported OS - #34
- Fixed bugs detected by cppcheck - #33
- Fixes typos. - #32
> Updated changelog and README.md for v1.0.37

- ChangeLog
n/a
- Fixed a bug in build_helper.sh - #36
> Updated changelog for v1.0.38

- ChangeLog
n/a
- Fixed centos8 build and removed centos6 build - #38
> Updated changelog for v1.0.39

- feature.md
N/A
This PR fixes markup syntax errors.
> Fixes markup syntax errors

- .github/workflows/ci.yml
- .github/workflows/docker_helper.sh
- .github/workflows/imagetypevars.sh
- README.md
- buildutils/Dockerfile.templ.in
- configure.ac
n / a
In Github Actions, I added the process to build Docker Image on DockerHub and push it.
> Added docker build and push in Github Actions

- ChangeLog
n/a
- Fixed ci.yml for Docker image build/push - #45
- Added docker build and push in Github Actions - #43
- Functional improvements and bug fixes - #42
> Updated changelog for v1.0.40

- .gitignore
- buildutils/Dockerfile.templ.in
#43
Fixed a bug that the file path of Dockerfile is wrong.
And also updated .gitignore.
> Fixed a bug in Dockerfile.templ.in and updated .gitignore

- ChangeLog
n/a
- Fixed a bug in Dockerfile.templ.in and updated .gitignore - #46
> Updated changelog for v1.0.41

- .github/workflows/ci.yml
- .github/workflows/docker_helper.sh
- .github/workflows/imagetypevars.sh
- buildutils/Dockerfile.templ.in
n/a
Fixed an issue with Docker image builds on Github Actions.
At the time of PR, it was modified so that it could be built with the source code of the original repository.
We also shared docker_helper.sh with other Antpickax products.
> Fixed a bug in Docker image build

- ChangeLog
n/a
- Fixed a bug in Docker image build - #50
> Updated changelog for v1.0.43

- configure.ac
- lib/flckbaselist.tcc
- lib/flckshm.cc
- lib/flckshm.h
- lib/flckthread.cc
n/a
Fixed an error output by cppcheck 2.7.
> Fixed code for cppcheck 2.7 error

- .gitignore
- Makefile.am
- configure.ac
n/a
Updated .gitignore Makefile.am configure.ac files.
> Updated .gitignore Makefile.am configure.ac

- lib/flckbaselist.tcc
- lib/flckpidcache.h
- lib/rwlockrcsv.h
- tests/fcntl_mptest.cc
- tests/fcntl_mttest.cc
- tests/mptest.cc
- tests/mttest.cc
n/a
Fixed errors reported by cppcheck 2.9.
> Fixed errors reported by cppcheck 2.9

- .github/workflows/ostypevars.sh
> Re-updated github actions process

- .github/workflows/build_helper.sh
- .github/workflows/ostypevars.sh
#63 #64
Changed some variable definitions of internal processing of `GithubActions`.
> Re-updated github actions process(2)

- .github/workflows/build_helper.sh
#63 #64 #65
Changed some variable definitions of internal processing of `GithubActions`.
> Re-updated github actions process(3)

- .github/workflows/ci.yml
- .github/workflows/docker_helper.sh
- .github/workflows/ostypevars.sh
#67 
Fixed a bug in `docker_helper.sh`.
Also modified `ci.yml` and `ostypevars.sh` to revert back to the original supported OS.
The OS will change to a new support range when a series of fixes is completed.
> Fixed a bug in docker_helper.sh and ci.yml

- .github/workflows/build_helper.sh
#70 
There was a correction omission of #70, so I updated it.
> Fixed a bug in build_helper.sh

- .github/workflows/docker_helper.sh
- .github/workflows/imagetypevars.sh
- .github/workflows/ostypevars.sh
- Makefile.am
- buildutils/make_description.sh
- buildutils/make_variables.sh
- lib/flckdbg.cc
- lib/flckthread.cc
- lib/flckutil.cc
- tests/cond_mptest.cc
- tests/cond_mttest.cc
- tests/fcntl_mptest.cc
- tests/fcntl_mttest.cc
- tests/fullocktest.cc
- tests/mptest.cc
- tests/mttest.cc
- tests/singletest.cc
- tests/test.sh
n/a
Reviewed `ShellCheck` and `CppCheck` processing, and changed the configuration file.
Some found bugs are also fixed.
> Added ShellCheck processing and reviewed cppcheck

- Makefile.am
#72
Fixed a bug with `CppCheck` processing and updated `Makefile.am`.
> Updated Makefile.am about cppcheck

- buildutils/rules.in
n/a
Fixed a typo in the `rule.in` file for `debian` packages.
> Fixed a bug in rule.in file for debian packaging

- .github/workflows/build_helper.sh
- .github/workflows/ci.yml
- .github/workflows/docker_helper.sh
- .github/workflows/imagetypevars.sh
- .github/workflows/ostypevars.sh
- buildutils/APKBUILD.templ.in
- buildutils/Dockerfile.templ.in
- buildutils/alpine_build.sh
- buildutils/debian_build.sh
- configure.ac
n/a
Supported the ALPINE package.
Changed to run `image build` after the `build` task.
`image build` has been changed to install packages from packagecloud.io and create an image.
(No longer build from source code.)
Added ALPINE to the supported OS and changed other distributions to the latest version.
> Changed CI process flow/OSs and added Alpine OS

- .github/workflows/ci.yml
- .github/workflows/ostypevars.sh
n/a
Added support for Fedora 37 and dropped support for Fedora 35.
> Supported fedora 37 and dropped support for fedora 35dropped

- .github/workflows/build_helper.sh
n/a
Fixed a bug in the package publish process.
> Fixed a bug about publishing in build_helper.sh

- .github/workflows/build_helper.sh
- .github/workflows/imagetypevars.sh
n/a
Fixed bugs in `build_helper.sh` and `imagetypevars.sh`.
> Fixed bugs in build_helper.sh and imagetypevars.sh

- ChangeLog
#82
- Fixed bugs in build_helper.sh and imagetypevars.sh - #85
> Updated changelog for v1.0.46

- buildutils/APKBUILD.templ.in
n/a
Fixed package dependencies in ALPINE packages and Docker images.
> Fixed package dependency for ALPINE package

- ChangeLog
n/a
- Fixed package dependency for ALPINE package - #87
> Updated changelog for v1.0.47

- .github/workflows/imagetypevars.sh
- buildutils/APKBUILD.templ.in
n/a
Fixed package dependencies in ALPINE packages and Docker images.
> Fixed package dependency and docker image for ALPINE

- ChangeLog
n/a
- Fixed package dependency and docker image for ALPINE - #89
> Updated changelog for v1.0.48

- buildutils/APKBUILD.templ.in
- buildutils/Makefile.am
- buildutils/alpine_build.sh
n/a
Fixed and updated scripts, packages, dependencies, etc. related to `ALPINE`.
> Updated building/packaging logic for ALPINE

- ChangeLog
n/a
- Updated building/packaging logic for ALPINE - #91
> Updated changelog for v1.0.49

- .github/workflows/build_helper.sh
- .github/workflows/docker_helper.sh
- buildutils/debian_build.sh
- buildutils/rpm_build.sh
n/a
Updated CI (`Github Actions`) auxiliary scripts.
> Updated build helper scripts on CI process

- ChangeLog
n/a
- Updated build helper scripts on CI process - #93
> Updated changelog for v1.0.50

- ChangeLog
n/a
- Fixed .gitignore to exclude APKBUILD.templ - #95
> Updated changelog for v1.0.51

- ChangeLog
n/a
- Updated tool scripts and support OSs - #97
> Updated changelog for v1.0.52

- .github/workflows/ostypevars.sh
#97 
Fixed `Debian:12` packaging problem.
> Fixed a bug about packaging

- ChangeLog
n/a
- Fixed a bug about packaging - #99
> Updated changelog for v1.0.53

- .github/workflows/ci.yml
- .github/workflows/ostypevars.sh
n/a
Supported OS has been changed.
- Does not support fedora 36
- Added support for fedora 38
- Does not support Ubuntu 18.04
> Changed support OS (fedora and ubuntu)

- ChangeLog
n/a
- Changed support OS (fedora and ubuntu) - #101
> Updated changelog for v1.0.54

- .github/workflows/build_helper.sh
n/a
- Fixed `build_helper.sh`
The minimum Ruby version required for the `package_cloud` command has been changed to 2.6, and `build_helper.sh` has been modified accordingly.
> Fixed build_helper.sh for upgrading ruby required package_cloud

- ChangeLog
n/a
- Fixed a bug in build_helper.sh - #105
> Updated changelog for v1.0.56

- ChangeLog
#106
- Fixed a bug in build_helper.sh - #105
> Re-Updated changelog for v1.0.56

- .github/workflows/ci.yml
- .github/workflows/ostypevars.sh
n/a
Supported OS has been changed.
- Does not support fedora 37
- Added support for fedora 39
- Added support for Alpine 3.19
- Changed Alpine's Docker Image to 3.19
And changed the version of actions/checkout.
> Changed support OS (fedora and alpine)

- .github/workflows/ci.yml
- Makefile.am
- lib/flckbaselist.tcc
- lib/flckdbg.cc
- lib/flcklistfilelock.h
- lib/flcklistlocker.h
- lib/flcklistncond.h
- lib/flcklistnmtx.h
- lib/flcklistofflock.cc
- lib/flcklistofflock.h
- lib/flcklistwaiter.h
- lib/flckshm.cc
- lib/flckshm.h
- lib/flckshminit.cc
- lib/flckutil.h
- lib/rwlockrcsv.cc
- tests/cond_mptest.cc
- tests/fcntl_mptest.cc
- tests/mptest.cc
n/a
Fixed an error reported by cppcheck.
Also, there was a problem with Makefile.am, so I fixed it.
Changed the version of docker/setup-buildx-action.
> Fixed cppcheck error and Makefile.am

- ChangeLog
n/a
- Fixed cppcheck error and Makefile.am - #111
- Changed support OS (fedora and alpine) - #110
> Updated changelog for v1.0.58

- .github/workflows/ci.yml
n/a
The version of docker/login-action has been changed.
> Updated docker/login-action from v2 to v3

- ChangeLog
#112
- Updated docker/login-action from v2 to v3 - #113
- Fixed cppcheck error and Makefile.am - #111
- Changed support OS (fedora and alpine) - #110
> Re-updated changelog for v1.0.58

- ChangeLog
n/a
- Fixed Makefile.am about cppcheck version - #115
> Updated changelog for v1.0.59

- .github/workflows/build_helper.sh
- .github/workflows/ci.yml
- .github/workflows/docker_helper.sh
- .github/workflows/ostypevars.sh
- buildutils/alpine_build.sh
- buildutils/make_description.sh
- lib/flckbaselist.tcc
- tests/fcntl_mptest.cc
- tests/fcntl_mttest.cc
- tests/mptest.cc
- tests/mttest.cc
n/a
The supported operating systems have been changed as follows.
Other operating systems are not supported and packages will not be provided.
- ubuntu 20.04 (Focal Fossa)
- ubuntu 22.04 (Jammy Jellyfish)
- ubuntu 24.04 (Noble Numbat)  
- debian 11 (Bullseye)
- debian 12 (Bookworm)
- RockyLinux 8
- RockyLinux 9  
- Fedora 40
- Fedora 41  
- ALPINE 3.18
- ALPINE 3.19
- ALPINE 3.20  
In addition, the Docker images provided have been changed to the following two OS bases.
- Ubuntu 24.04
- ALPINE 3.20
In conjunction with this, we have corrected the related source code and bugs detected by the tool.
> Changed supported OS and modified some codes

- feature.md
- featureja.md
#117
Updated feature.md for support OSes
> Updated feature.md for support OSes

- ChangeLog
n/a
- Changed supported OS and modified some codes - #117
> Updated changelog for v1.0.60

- ChangeLog
n/a
- Added a directory to be created by the package - #120
> Updated changelog for v1.0.61

- ChangeLog
n/a
- Changed support OSes and Fixed scripts, etc - #122
> Updated changelog for v1.0.62

- ChangeLog
n/a
- Avoided latest cppcheck error which maybe a false positive - #125
> Updated changelog for v1.0.63
